### PR TITLE
Registers for slave-mode

### PR DESCRIPTION
**Pull request by an-dr**
Adding registers. Registers are a separate class. The logic of working with them consists of two steps: selection of the register and read/write operation

### CODE REVIEW

**Comment by thexeno** [comment]
Hi,

At the moment I think is better to keep the library separated to not mix the layers in the protocol.
I would refine it to provide explicit compatibility with the HardWire (or others as well), then propose it to the Arduino community.

I would be happy to provide some interfaces for other libraries like yours, if viceversa is not possible, but not merging them together yet. As said, it is very helpful, but would be not nice if completely integrated into the I2C, as I would like to use it for other protocols as well, like SPI, or why not the serial.

The concept I have is to be able to be used in different protocols, when in slave: data stream, random-access (like with registers) ecc.

It would be awesome to be able to just include a "random-access" library and use it with the HardWire, or others, maybe custom or official SPI, to allow interchangeability. 

I am working on a C-based portable framework, (so not much time on Arduino for now) and I was actually thinking to bring the register system as a middle layer functionality, in the same separated way as  I briefly described before.

Cheers!

**Comment by an-dr** [comment]
Ok, probably you are right mixing it up is not the best way. I'll do it another way

**Comment by an-dr** [comment]
@thexeno PTAL at more gentle integration of my registers. In case of integration with other interface I could create a repository for VirtualRegisters and you add it as a submodule whatever you want.

Also I can provide events handling in the repo, to do something like
```
  Wire.onReceive(VirtualRegsWireReceive); // register event
  Wire.onRequest(VirtualRegsWireRequest); // register event
```
Not an ideal solution, will help to encapsulate Reg's logic.
Another option is to make unversal  handles, getting interface-specific read_byte and write_byte functions like:
```
VirtualRegsReceiveHandling(read_func, write_func)
VirtualRegsRequestHandling(write_func)
```
and then

```
void receiveEvent(int howMany) {
  VirtualRegsReceiveHandling(&(Wire.read),&(Wire.write));
}

void requestEvent() {
  VirtualRegsRequestHandling(&(Wire.write));
}

```

**Comment by thexeno** [comment]
Hi, I took a peek at your example. Nice cleaner way.
If I'm correct, seems you are not using anything specific to the HardWire
(i.e. can be used in the Wire).
So, why merging specifically in the HardWire, or in an already existing
library anyway? By checking the example, you are using 2 headers (
HardWire.h   and  VirtualRegs.h), so I believe you can actually request to
insert your own library in the Arduino LM so for example one can play
around with the nicer register model regardless the interface.

**Pull request closed without merging**
